export const ANALYTICS_LOADING = 'ANALYTICS_LOADING';
export const ANALYTICS_SUCCESS = 'ANALYTICS_SUCCESS'
export const ANALYTICS_NOT_FOUND = 'ANALYTICS_NOT_FOUND';
export const ANALYTICS_ERROR = 'ANALYTICS_NOT_FOUND';